// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMapRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMapRequest) Reset()         { *m = GetMapRequest{} }
func (m *GetMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetMapRequest) ProtoMessage()    {}
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_73697e69bd17a7ab, []int{0}
}
func (m *GetMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMapRequest.Unmarshal(m, b)
}
func (m *GetMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMapRequest.Marshal(b, m, deterministic)
}
func (dst *GetMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMapRequest.Merge(dst, src)
}
func (m *GetMapRequest) XXX_Size() int {
	return xxx_messageInfo_GetMapRequest.Size(m)
}
func (m *GetMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMapRequest proto.InternalMessageInfo

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_73697e69bd17a7ab, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type GetMapResponse struct {
	M                    map[string]*Message `protobuf:"bytes,1,rep,name=m,proto3" json:"m,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetMapResponse) Reset()         { *m = GetMapResponse{} }
func (m *GetMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetMapResponse) ProtoMessage()    {}
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_73697e69bd17a7ab, []int{2}
}
func (m *GetMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMapResponse.Unmarshal(m, b)
}
func (m *GetMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMapResponse.Marshal(b, m, deterministic)
}
func (dst *GetMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMapResponse.Merge(dst, src)
}
func (m *GetMapResponse) XXX_Size() int {
	return xxx_messageInfo_GetMapResponse.Size(m)
}
func (m *GetMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMapResponse proto.InternalMessageInfo

func (m *GetMapResponse) GetM() map[string]*Message {
	if m != nil {
		return m.M
	}
	return nil
}

func init() {
	proto.RegisterType((*GetMapRequest)(nil), "api.GetMapRequest")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterType((*GetMapResponse)(nil), "api.GetMapResponse")
	proto.RegisterMapType((map[string]*Message)(nil), "api.GetMapResponse.MEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error) {
	out := new(GetMapResponse)
	err := c.cc.Invoke(ctx, "/api.Service/GetMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	GetMap(context.Context, *GetMapRequest) (*GetMapResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_GetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Service/GetMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetMap(ctx, req.(*GetMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMap",
			Handler:    _Service_GetMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_73697e69bd17a7ab) }

var fileDescriptor_api_73697e69bd17a7ab = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xe2, 0xe7, 0xe2, 0x75, 0x4f,
	0x2d, 0xf1, 0x4d, 0x2c, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0xe2, 0xe4, 0x62, 0xf7,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xaa, 0xe3, 0xe2, 0x83, 0xc9, 0x15, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0x69, 0x70, 0x31, 0xe6, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x49, 0xe9,
	0x81, 0x4c, 0x42, 0x95, 0xd7, 0xf3, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x62, 0xcc, 0x95, 0x72,
	0xe2, 0x62, 0x83, 0x70, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x40, 0x4c, 0x21, 0x25, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0x6e, 0x23, 0x1e, 0xb0, 0x49, 0x50, 0x4b, 0x83, 0x20, 0x52, 0x56, 0x4c, 0x16, 0x8c,
	0x46, 0x36, 0x5c, 0xec, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x86, 0x5c, 0x6c, 0x10,
	0xab, 0x84, 0x84, 0x50, 0xec, 0x05, 0xbb, 0x59, 0x4a, 0x18, 0x8b, 0x5b, 0x92, 0xd8, 0xc0, 0xbe,
	0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x95, 0x5b, 0x78, 0xf2, 0x00, 0x00, 0x00,
}
